proxies:
  - name: "VLESS-Reality"
    type: "vless"
    server: "server_ip" #服务器地址
    port: 443
    udp: true
    uuid: "" # UUID
    flow: "xtls-rprx-vision"
    tls: true
    servername: ""
    alpn: ["h2", "http/1.1"]
    client-fingerprint: "chrome"
    network: "tcp"
    reality-opts:
      public-key: "" # 运行mihomo generate reality-keypair 命令生成，取PublicKey填写
      short-id: ""
      support-x25519mlkem768: true # 支持X25519MLKEM768
