proxies:
  - name: "Shadowquic"
    type: shadowquic
    server: "" #IP
    port: 443
    udp: true
    username: ""
    password: ""
    quic-versions: [v2]
    congestion-controller: "bbr"
    sni: "test.com" #JLS Sni
    zero-rtt: true
    alpn: [h3]
