listeners:
  - name: "hysteria2-server"
    type: hysteria2
    port: 443
    listen: "0.0.0.0"
    users:
      user1: "password1"
      user2: "password2"
    # 服务端限速
    up: 1000
    down: 1000
    ignore-client-bandwidth: true #忽略客户端速率协商，只使用bbr
    # masquerade: "https://example.com:443" #伪装地址
    alpn: ["h3"]
    certificate: "./server.crt"
    private-key: "./server.key"
    # 如果填写则开启ech(可由 mihomo generate ech-keypair <明文域名> 生成)
    ech-key: |
      -----BEGIN ECH KEYS-----
      ACATwY30o/RKgD6hgeQxwrSiApLaCgU+HKh7B6SUrAHaDwBD/g0APwAAIAAgHjzK
      madSJjYQIf9o1N5GXjkW4DEEeb17qMxHdwMdNnwADAABAAEAAQACAAEAAwAIdGVz
      dC5jb20AAA==
      -----END ECH KEYS-----
